ReadLine/Controllers/BookInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReadLine.Models;
using ReadLine.Models.ViewModels;

namespace ReadLine.Controllers
{
    public class BookInfoController : BookControllerBase
    {
        public BookInfoController(MainDataContext context) : base(context){ }
        public async Task<IActionResult> Index(long id)
        {
            var book = context.Books.Include(b => b.Author).Include(b => b.Tags).Include(b => b.Category).First(b => b.BookId == id);
            BookViewModel bookViewModel = new BookViewModel(book);
            return View(bookViewModel);
        }
    }
}

ReadLine/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReadLine.Models;
using ReadLine.Models.ViewModels;

namespace ReadLine.Controllers
{
    public class HomeController : BookControllerBase
    {
        public HomeController(MainDataContext context): base(context) { }
        public async Task<IActionResult> Index()
        {
            List<BookViewModel> books = await context.Books.Include(b => b.Author).Include(b => b.Tags).Include(b => b.Category)
                .Select(book => new BookViewModel(book)).ToListAsync();
            return View(books);
        }

        [HttpPost]
        public async Task<IActionResult> SearchForm(string search = "")
        {
            List<Book> books = await context.Books.Include(b => b.Author).Include(b => b.Tags).Include(b => b.Category).ToListAsync();
            List<BookViewModel> result = books.
            Where(b =>
            search.ToString().ToLower().Split(' ', StringSplitOptions.RemoveEmptyEntries).
            Intersect(b.Title.ToLower().Split(' ', StringSplitOptions.RemoveEmptyEntries)).Count() > 0).
            Select(book => new BookViewModel(book))
            .ToList();
            return View("Index", result);
        }
    }
}

ReadLine/Views/Home/Index.cshtml
@model List<BookViewModel>
<div class="row">
    <h2 style="margin: 20px;">Каталог</h2>
    <hr />
</div>
<div class="row">
    <div class="col-md-2">
        <p>Menu</p>
    </div>
    <div class="col-md-10 align-items-center" style="width: 70%;">
        <nav class="navbar navbar-expand-lg" style="margin: 16px;">
            <div class="container-fluid">
                <form action="@Url.Action("searchform")" class="d-flex" method="post">
                    <input class="form-control me-2" style="min-width: 600px;" name="search" type="search" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-success" type="submit">Поиск</button>
                </form>
            </div>
        </nav>
        @if (Model.Count() == 0)
        {
            <p>Ничего не найдено.</p>
            <a class="btn btn-secondary" href="@Url.Action("Index")">На главную</a>
        }
        <div class="container" style="display: flex; flex-wrap: wrap; justify-content: flex-start; align-items: start; padding: 2.5rem 5%; ">
            @foreach (var b in Model.Take(30))
            {
                <div class="box" style="flex: 0 0 12rem; position: relative; margin: 1rem; min-width: 120px">
                    <div class="card" >
                        <img src="/img/default_cover.png" class="card-img-top rounded-2" alt="Обложка отсутствует" style="max-width: 92%; margin: 10px;">
                        <div class="card-body">
                            <a href="@Url.Action("Index", "BookInfo", new{ id = b.BookId })" class="d-inline-block text-truncate" style="max-width: 150px;">@b.Title </a>
                            <p class="card-text">@(b.AuthorSurname + " " + b.AuthorName)</p>
                            <p class="card-text">@b.PagesCount стр.</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>